name: build

on:
  push:
    branches:
      - trunk
    paths:
      - .github/workflows/build.yml
  pull_request:
    branches:
      - trunk
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v3

      - name: "install pnpm"
        uses: pnpm/action-setup@v2

      - name: "Install dependencies"
        run: pnpm install

      - name: "build"
        run: pnpm run build:rollup

      - name: archive output dir
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r build.zip output

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build.zip
          path: build.zip
