name: release webext

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: release webext
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v3

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: src
          filename: "{name}-{version}.xpi"

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: target.xpi
          path: ${{ steps.web-ext-build.outputs.target }}
