name: Build WebExtension

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: release webext
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     
     - name: Install Node.js
       uses: actions/setup-node@v3
       with:
         node-version: 16
          
     - name: Install pnpm
       uses: pnpm/action-setup@v2
       with:
         version: 6.0.2

     - name: install deps
       run: pnpm install

     - name: build
       run: pnpm run build

     - name: Create release 
       uses: softprops/action-gh-release@v1
       env:
        GIRHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
        draft: true
        files: |
          ./web-ext-artifacts/tulips1calil-webext-${{ github.ref }}.zip
