name: release webext

on:
  push:
    tags:
      - 'v*.*.*'
    paths:
      - .github/workflows/release.yml
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  packaging-firefox:
    needs: [build]
    name: packing webext (firefox)
    runs-on: ubuntu-latest
    outputs:
      xpiFileName: ${{ steps.web-ext-sign.outputs.target }}
    steps:
      - name: Download math result for build job
        uses: actions/download-artifact@v3
        with:
          name: build.zip

      - uses: montudor/action-zip@v1
        with:
          args: unzip -qq build.zip

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: output
      
      - name: "web-ext sign"
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          channel: unlisted
          apiKey: ${{ secrets.AMO_SIGN_KEY }}
          apiSecret: ${{ secrets.AMO_SIGN_SECRET }}
          timeout: 900000
      
      - name: echo
        run: |
          echo ${{ steps.web-ext-sign.outputs.target }}
      
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ steps.web-ext-sign.outputs.target }}
  
  packaging-chrome:
    needs: [build]
    name: packing webext (chrome)
    runs-on: ubuntu-latest
    outputs:
      crxFileName: "${{ steps.packExtensionDir.outputs.extensionName }}-${{ steps.packExtensionDir.outputs.extensionVersion }}.crx"
    steps:
      - name: Download math result for build job
        uses: actions/download-artifact@v3
        with:
          name: build.zip

      - uses: montudor/action-zip@v1
        with:
          args: unzip -qq build.zip
  
      - id: packExtensionDir
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: "./output"
          zipFilePath: "chrome.zip"

      - id: makeCRX
        uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: "chrome.zip"
          crxFilePath: "${{ steps.packExtensionDir.outputs.extensionName }}-${{ steps.packExtensionDir.outputs.extensionVersion }}.crx"
          privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}
      
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: "${{ steps.packExtensionDir.outputs.extensionName }}-${{ steps.packExtensionDir.outputs.extensionVersion }}.crx"

  release:
    name: create release note
    needs: [packaging-firefox, packaging-chrome]
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for packaging-firefox job
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.packaging-firefox.outputs.xpiFileName }}

      - name: Download math result for packaging-chrome job
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.packaging-chrome.outputs.crxFileName }}

      - name: "Create Release Draft"
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
          draft: true
          files: |
            ${{ needs.packaging-firefox.outputs.xpiFileName }}
            ${{ needs.packaging-chrome.outputs.crxFileName }}
